services:
  api:
    container_name: habits_test_api
    environment: 
      - PGUSER=team1
      - PGHOST=db
      - PGPASSWORD=team1_password
      - PGDATABASE=habits
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: habits_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=habits
      - POSTGRES_PASSWORD=team1_password
volumes:
  test_db:
networks: 
  default:
    name: habits_test_test